# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.12.0 on Wed Feb 15 04:19:06 2023
# Model: Habitat Quality

import logging
import sys

import natcap.invest.habitat_quality
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    # 'access_vector_path': '',
    'half_saturation_constant': '0.5',
    'lulc_bas_path': '',
    'lulc_cur_path': r'/workspace/haowei/espandInVEST/InvestModel/landcover.tif',
    'lulc_fut_path': '',
    'n_workers': '40',
    'results_suffix': '',
    'sensitivity_table_path': r'/workspace/haowei/espandInVEST/InvestModel/sensitivity.csv',
    'threats_table_path': r'/workspace/haowei/espandInVEST/InvestModel/threats.csv',
    'workspace_dir': r'/workspace/haowei/espandInVEST/InvestModel',
}

if __name__ == '__main__':
    natcap.invest.habitat_quality.execute(args)
